name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go
    - name: checkout
      uses: actions/checkout@v2
    - name: deps
      run: go mod vendor
    - name: build
      run: go build -x -v .
